const usersSection = {
    view:()=>{
        return m("div.card.w-full.p-6.bg-base-100.shadow-xl.mt-2",
            [
                m("div.text-xl.font-semibold.inline-block",
                    [
                        "Active Members",
                        m("div.inline-block.float-right",
                            m("div.inline-block.float-right",
                                m("button.btn.px-6.btn-sm.normal-case.btn-primary",
                                    "Invite New"
                                )
                            )
                        )
                    ]
                ),
                m("div.divider.mt-2"),
                m("div.h-full.w-full.pb-6.bg-base-100",
                    m("div.overflow-x-auto.w-full",
                        m("table.table.w-full",
                            [
                                m("thead",
                                    m("tr",
                                        [
                                            m("th",
                                                "Name"
                                            ),
                                            m("th",
                                                "Email Id"
                                            ),
                                            m("th",
                                                "Joined On"
                                            ),
                                            m("th",
                                                "Role"
                                            ),
                                            m("th",
                                                "Last Active"
                                            )
                                        ]
                                    )
                                ),
                                m("tbody",
                                    [
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/1-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "Alex"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "alex@dashwind.com"
                                                ),
                                                m("td",
                                                    "05 Jun 2023"
                                                ),
                                                m("td",
                                                    m("div.badge.badge-primary",
                                                        "Owner"
                                                    )
                                                ),
                                                m("td",
                                                    "5 hr ago"
                                                )
                                            ]
                                        ),
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/2-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "Ereena"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "ereena@dashwind.com"
                                                ),
                                                m("td",
                                                    "31 May 2023"
                                                ),
                                                m("td",
                                                    m("div.badge.badge-secondary",
                                                        "Admin"
                                                    )
                                                ),
                                                m("td",
                                                    "15 min ago"
                                                )
                                            ]
                                        ),
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/3-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "John"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "jhon@dashwind.com"
                                                ),
                                                m("td",
                                                    "26 May 2023"
                                                ),
                                                m("td",
                                                    m("div.badge.badge-secondary",
                                                        "Admin"
                                                    )
                                                ),
                                                m("td",
                                                    "20 hr ago"
                                                )
                                            ]
                                        ),
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/4-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "Matrix"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "matrix@dashwind.com"
                                                ),
                                                m("td",
                                                    "21 May 2023"
                                                ),
                                                m("td",
                                                    m("div.badge",
                                                        "Manager"
                                                    )
                                                ),
                                                m("td",
                                                    "1 hr ago"
                                                )
                                            ]
                                        ),
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/5-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "Virat"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "virat@dashwind.com"
                                                ),
                                                m("td",
                                                    "16 May 2023"
                                                ),
                                                m("td",
                                                    m("div.badge.badge-accent",
                                                        "Support"
                                                    )
                                                ),
                                                m("td",
                                                    "40 min ago"
                                                )
                                            ]
                                        ),
                                        m("tr",
                                            [
                                                m("td",
                                                    m("div.flex.items-center.space-x-3",
                                                        [
                                                            m("div.avatar",
                                                                m("div.mask.mask-circle.w-12.h-12",
                                                                    m("img[src='https://reqres.in/img/faces/6-image.jpg'][alt='Avatar']")
                                                                )
                                                            ),
                                                            m("div",
                                                                m("div.font-bold",
                                                                    "Miya"
                                                                )
                                                            )
                                                        ]
                                                    )
                                                ),
                                                m("td",
                                                    "miya@dashwind.com"
                                                ),
                                                m("td",
                                                    "06 May 2023"
                                                ),
                                                m("td",
                                                    m("div.badge.badge-accent",
                                                        "Support"
                                                    )
                                                ),
                                                m("td",
                                                    "5 hr ago"
                                                )
                                            ]
                                        )
                                    ]
                                )
                            ]
                        )
                    )
                )
            ]
        )
    }
}

export default usersSection;